### ISSUE TITLE
Mapper 경로문제

### ISSUE THREAD

**Issue by Young5097** [Young5097/eDrink24-server#2]
기존엔 src 아래 config 파일에  mapper.xml, mapper.java(interface)를 모두 저장하였지만
갑자기 실행되지 않는 문제 발생

=> 2024-07-24 12:34:13.794 DEBUG 11736 --- [  restartedMain] o.mybatis.spring.SqlSessionFactoryBean   : Property 'mapperLocations' was not specified.

< 해결 > 
resources/config에 xxxMapper.xml, src 아래 config에 xxxMapper.java로 경로를 나눠주니 해결됨
기존에 되던게 안되는 이유는 모르겠음

**Comment by giuk-kim2** [comment]
asdad

**Comment by Young5097** [comment]
해결완료

**Comment by Young5097** [comment]
끝

**Comment by giuk-kim2** [comment]
good
